### ISSUE TITLE
Open codemirror theme to be overriden

### ISSUE THREAD

**Issue by robsonsobral** [voraciousdev/vue-markdown-editor#7]
Please, is it possible to allow us to choose a codemirror theme?

Couldn't it be merged on default options?

```js
options() {
      return {
        addModeClass: true,
        extraKeys: {
          // use spaces instead of tabs
          // https://github.com/codemirror/CodeMirror/issues/988#issuecomment-14921785
          'Shift-Tab': (instance) => {
            instance.indentSelection('subtract')
          },
          Tab: (instance) => {
            if (instance.somethingSelected()) {
              instance.indentSelection('add')
            } else {
              instance.replaceSelection(Array(instance.getOption('tabSize') + 1).join(' '), 'end', '+input')
            }
          },
        },
        indentUnit: this.config.tabSize,
        indentWithTabs: false,
        keyMap: this.keyMap,
        lineWrapping: true,
        mode: {
          name: this.config.mode,
          // fencedCodeBlockDefaultMode: 'html',
          highlightFormatting: true,
        },
        singleCursorHeightPerLine: true,
        tabSize: this.config.tabSize,
        theme: 'one-mixed',
      }
    },
```

Thank you!

**Comment by davidmyersdev** [comment]
I can make this change, but I should probably mention that I am working on replacing the implementation here with CodeMirror 6. CM6 is **not** backward compatible with CM5, and implementing a separate theme will require a different configuration interface.

**Comment by davidmyersdev** [comment]
@robsonsobral This is now possible in [`v0.3.1`](https://github.com/voraciousdev/vue-markdown-editor/releases/tag/v0.3.1). I just realized the config setting could be a little confusing, because there is a `theme` attribute for specifying dark/light mode. You need to use the `settings` attribute with the `theme` _key_ inside the config object. Here is an example.

```vue
<MarkdownEditor v-model="markdown" theme="dark" :settings="{ theme: 'another-theme' }" />
```

Also, you will need to load the CSS file in the consuming app for the alternative theme you provide.
